### ISSUE TITLE
Unclear documentation for natural.date.delta

### ISSUE THREAD

**Issue by raxod502** [tehmaze/natural#16]
I have this from [the example](http://natural.readthedocs.io/en/latest/natural/date.html) for `natural.date.delta`:

```
>>> (x,y) = delta(_to_datetime('2012-06-13T15:24:17'),     _to_datetime('2013-12-11T12:34:56'))
>>> print(x)
77 weeks
>>> int(y)
-594639
```

I get that it returns a tuple whose first element is the string I want, but… what is `-594639`?

**Comment by StephenBrown2** [comment]
Yeah, that certainly isn't specified in the docs, it should have a :returns: line in the docstring for it.

Looking at [the code](https://github.com/tehmaze/natural/blob/master/natural/date.py#L132-L263), it looks like that is the timedelta in seconds.
