### ISSUE TITLE
Python3 FutureWarning: split() requires a non-empty pattern match in constant.py

### ISSUE THREAD

**Issue by efloehr** [tehmaze/natural#19]
In line 299 of constant.py the regular expression split "r'[\n\s]*'" should be replaced with "r'[\n\s]*".

See this stackoverflow question:

https://stackoverflow.com/questions/47564710/regular-expression-split-futurewarning-split-requires-a-non-empty-pattern-m?rq=1

**Comment by tehmaze** [comment]
Fixed in #18
